version: '3.7'
services: 
    jenkins:
        build: .
        image: myjenkins-blueocean:1.1
        ports: 
            - "8080:8080"
            - "50000:50000"
        networks: 
            - jenkins
        container_name: my-jenkins
        environment: 
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1
        volumes: 
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        depends_on: 
            - docker

    docker:
        image: docker:dind
        privileged: true
        ports: 
            - "3000:3000"
            - "2376:2376"
        networks: 
            - jenkins
        container_name: my-docker
        environment: 
            DOCKER_TLS_CERTDIR: /certs
        volumes: 
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client
            - docker-data:/var/lib/data

volumes: 
    jenkins-data:
    docker-certs:
    docker-data:

networks: 
    jenkins: